spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://happyaging.c5k0a6owcdit.ap-northeast-2.rds.amazonaws.com:3306/happyAging?useUnicode=true&characterEncoding=utf8mb4
  #    url: jdbc:mariadb://localhost:3306/happyaging
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      ddl-auto: create
      show_sql: true
  config:
    additional-location: classpath:application-secret.yml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
