spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://happyaging.c5k0a6owcdit.ap-northeast-2.rds.amazonaws.com:3306/happyAging?useUnicode=true&characterEncoding=UTF-8
  #    url: jdbc:mariadb://localhost:3306/happyaging
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      ddl-auto: create
      show_sql: true
  config:
    additional-location: classpath:application-secret.yml