spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/happyaging
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: create
      show_sql: true
  config:
    additional-location: classpath:application-secret.yml
