spring:
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      ddl-auto: update
      show_sql: true
  config:
    additional-location: classpath:application-secret.yml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
