spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://maraidb-happyaging.c9miszrbndai.ap-northeast-2.rds.amazonaws.com:3306/happyaging?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mariadb://localhost:3306/happyaging
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      ddl-auto: create
      show_sql: true
  config:
    additional-location: classpath:application-secret.yml
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id